### ISSUE TITLE
Docs build broken on build server

### ISSUE THREAD

**Issue by ociaw** [ociaw/RandN#10]
The docsite fails to build on the build server, but not locally on my computer.
[https://builds.sr.ht/~ociaw/job/316214](https://builds.sr.ht/~ociaw/job/316214)
```
    Executing pipeline "Resources" (20/24) with 1 child module(s)
            Error while copying file /home/build/RandN/docs/input/assets/css/override.css: The process cannot access the file '/home/build/RandN/docs/output/assets/css/override.css' because it is being used by another process.
            Error while executing module CopyFiles
        Error while executing pipeline Resources
Exception during execution: System.AggregateException: One or more errors occurred. (One or more errors occurred. (The process cannot access the file '/home/build/RandN/docs/output/assets/css/override.css' because it is being used by another process.)) (The process cannot access the file '/home/build/RandN/docs/output/assets/css/override.css' because it is being used by another process.) ---> System.IO.IOException: The process cannot access the file '/home/build/RandN/docs/output/assets/css/override.css' because it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.RetryHelper.Retry[T](Func`1 func) in C:\Code\Wyam\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\RetryHelper.cs:line 22
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in C:\Code\Wyam\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 67
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass10_0.<Execute>b__1(IFile file) in C:\Code\Wyam\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 147
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by ociaw** [comment]
Resolved by 81f31928a9b633ed8f3b29ca17f9abf6baeffafa.
