### ISSUE TITLE
IndexOutOfRangeException when calling RandN.Rngs.ChaCha.NextUInt32()

### ISSUE THREAD

**Issue by mizrachiran** [ociaw/RandN#26]
Hi,

I get the following exception from time to time, now sure what is the root cause.

this is how i intantiate my _rng instance:
 var rng = ChaCha.GetChaCha8Factory().Create(ThreadLocalRng.Instance);
I call the following method: 
rng.NextUInt32()

Stack trace:
Exception has occurred: CLR/System.IndexOutOfRangeException
Exception thrown: 'System.IndexOutOfRangeException' in RandN.Core.dll: 'Index was outside the bounds of the array.'
   at RandN.Implementation.BlockBuffer32`2.NextUInt32()
   at RandN.Rngs.ChaCha.NextUInt32()

**Comment by ociaw** [comment]
I haven't been able to replicate this. Can you provide the .NET version, RandN version, and CPU architecture this is occurring on?

**Comment by mizrachiran** [comment]
It happened in a .net core asp app, running on Macbook pro M1. Don't have a repro, already changed my implementation.
